//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyKPITransaction
    {
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<System.Guid> KPIID { get; set; }
        public Nullable<decimal> PerformanceNumber { get; set; }
    }
}
