//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KPI()
        {
            this.PerformanceIndicators = new HashSet<PerformanceIndicator>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> StrategicObjectiveId { get; set; }
        public string KPI1 { get; set; }
        public bool IsActive { get; set; }
    
        public virtual StrategicObjective StrategicObjective { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PerformanceIndicator> PerformanceIndicators { get; set; }
    }
}
