//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Target
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> TeamId { get; set; }
        public Nullable<System.Guid> KPIID { get; set; }
        public Nullable<decimal> Target1 { get; set; }
        public Nullable<System.Guid> UOMId { get; set; }
    }
}
